-- DEHAX EDITOR PLATFORM — Supabase schema
-- Execute este arquivo no SQL Editor de um projeto novo do Supabase.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  email text,
  role text not null default 'member' check (role in ('member','admin')),
  plan text not null default 'free' check (plan in ('free','pro')),
  subscription_status text not null default 'inactive',
  subscription_id text,
  is_suspended boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,display_name,email)
  values(new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email,'@',1)), new.email)
  on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='admin' and is_suspended=false);
$$;

create table if not exists public.assets (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text default '',
  category text not null default 'Outros',
  subcategory text default '',
  tags text[] not null default '{}',
  media_type text not null default 'archive' check(media_type in ('audio','video','image','archive','project')),
  file_format text,
  file_size bigint,
  cover_url text,
  access_level text not null default 'pro' check(access_level in ('free','pro')),
  status text not null default 'draft' check(status in ('draft','published','paused')),
  download_enabled boolean not null default true,
  preview_enabled boolean not null default true,
  featured boolean not null default false,
  download_count bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.asset_files (
  asset_id uuid primary key references public.assets(id) on delete cascade,
  file_key text,
  preview_key text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tutorials (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text default '',
  category text default 'Edição',
  duration_label text default '',
  thumbnail_url text,
  access_level text not null default 'pro' check(access_level in ('free','pro')),
  status text not null default 'draft' check(status in ('draft','published','paused')),
  featured boolean not null default false,
  order_index integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tutorial_sources (
  tutorial_id uuid primary key references public.tutorials(id) on delete cascade,
  youtube_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.favorites (
  user_id uuid not null references public.profiles(id) on delete cascade,
  asset_id uuid not null references public.assets(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id,asset_id)
);

create table if not exists public.downloads (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  asset_id uuid references public.assets(id) on delete set null,
  action text not null default 'download',
  ip_hash text,
  created_at timestamptz not null default now()
);
create index if not exists downloads_user_date_idx on public.downloads(user_id,created_at desc);
create index if not exists downloads_asset_date_idx on public.downloads(asset_id,created_at desc);

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

insert into public.app_settings(key,value) values
  ('hero_youtube_id','""'::jsonb),
  ('pro_price','"19,90"'::jsonb),
  ('discord_url','""'::jsonb),
  ('whatsapp_url','""'::jsonb),
  ('download_daily_limit','500'::jsonb),
  ('global_downloads_enabled','true'::jsonb),
  ('maintenance_message','""'::jsonb)
on conflict(key) do nothing;

create or replace function public.increment_asset_download(asset_uuid uuid)
returns void language sql security definer set search_path=public as $$
  update public.assets set download_count=download_count+1 where id=asset_uuid;
$$;

-- Updated_at triggers
DO $$
BEGIN
  if not exists(select 1 from pg_trigger where tgname='profiles_updated_at') then create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at(); end if;
  if not exists(select 1 from pg_trigger where tgname='assets_updated_at') then create trigger assets_updated_at before update on public.assets for each row execute function public.set_updated_at(); end if;
  if not exists(select 1 from pg_trigger where tgname='asset_files_updated_at') then create trigger asset_files_updated_at before update on public.asset_files for each row execute function public.set_updated_at(); end if;
  if not exists(select 1 from pg_trigger where tgname='tutorials_updated_at') then create trigger tutorials_updated_at before update on public.tutorials for each row execute function public.set_updated_at(); end if;
  if not exists(select 1 from pg_trigger where tgname='tutorial_sources_updated_at') then create trigger tutorial_sources_updated_at before update on public.tutorial_sources for each row execute function public.set_updated_at(); end if;
END $$;

alter table public.profiles enable row level security;
alter table public.assets enable row level security;
alter table public.asset_files enable row level security;
alter table public.tutorials enable row level security;
alter table public.tutorial_sources enable row level security;
alter table public.favorites enable row level security;
alter table public.downloads enable row level security;
alter table public.app_settings enable row level security;

-- Drop policies if re-running this file.
drop policy if exists profiles_read on public.profiles;
drop policy if exists profiles_admin_update on public.profiles;
drop policy if exists assets_catalog on public.assets;
drop policy if exists assets_admin_insert on public.assets;
drop policy if exists assets_admin_update on public.assets;
drop policy if exists assets_admin_delete on public.assets;
drop policy if exists asset_files_admin on public.asset_files;
drop policy if exists tutorials_catalog on public.tutorials;
drop policy if exists tutorials_admin_insert on public.tutorials;
drop policy if exists tutorials_admin_update on public.tutorials;
drop policy if exists tutorials_admin_delete on public.tutorials;
drop policy if exists tutorial_sources_admin on public.tutorial_sources;
drop policy if exists favorites_read on public.favorites;
drop policy if exists favorites_insert on public.favorites;
drop policy if exists favorites_delete on public.favorites;
drop policy if exists downloads_read on public.downloads;
drop policy if exists settings_read on public.app_settings;
drop policy if exists settings_admin on public.app_settings;

create policy profiles_read on public.profiles for select using (id=auth.uid() or public.is_admin());
create policy profiles_admin_update on public.profiles for update using (public.is_admin()) with check (public.is_admin());

create policy assets_catalog on public.assets for select using (status='published' or public.is_admin());
create policy assets_admin_insert on public.assets for insert with check (public.is_admin());
create policy assets_admin_update on public.assets for update using (public.is_admin()) with check (public.is_admin());
create policy assets_admin_delete on public.assets for delete using (public.is_admin());
create policy asset_files_admin on public.asset_files for all using (public.is_admin()) with check (public.is_admin());

create policy tutorials_catalog on public.tutorials for select using (status='published' or public.is_admin());
create policy tutorials_admin_insert on public.tutorials for insert with check (public.is_admin());
create policy tutorials_admin_update on public.tutorials for update using (public.is_admin()) with check (public.is_admin());
create policy tutorials_admin_delete on public.tutorials for delete using (public.is_admin());
create policy tutorial_sources_admin on public.tutorial_sources for all using (public.is_admin()) with check (public.is_admin());

create policy favorites_read on public.favorites for select using (user_id=auth.uid() or public.is_admin());
create policy favorites_insert on public.favorites for insert with check (user_id=auth.uid());
create policy favorites_delete on public.favorites for delete using (user_id=auth.uid() or public.is_admin());

create policy downloads_read on public.downloads for select using (user_id=auth.uid() or public.is_admin());
create policy settings_read on public.app_settings for select using (true);
create policy settings_admin on public.app_settings for all using (public.is_admin()) with check (public.is_admin());

-- Explicit grants. Secrets/keys never live in these tables.
grant usage on schema public to anon, authenticated;
grant select on public.assets, public.tutorials, public.app_settings to anon, authenticated;
grant select on public.profiles, public.favorites, public.downloads to authenticated;
grant insert,delete on public.favorites to authenticated;
grant insert,update,delete on public.assets, public.tutorials, public.app_settings to authenticated;
grant select,insert,update,delete on public.asset_files, public.tutorial_sources to authenticated;
grant update on public.profiles to authenticated;
grant usage,select on sequence public.downloads_id_seq to authenticated;
revoke all on function public.increment_asset_download(uuid) from public, anon, authenticated;
grant execute on function public.increment_asset_download(uuid) to service_role;

-- Depois de criar sua primeira conta, transforme-a em admin:
-- update public.profiles set role='admin' where email='SEU_EMAIL';
