-- DEHAX EDITOR PLATFORM — Supabase schema
-- Execute este arquivo no SQL Editor de um projeto novo do Supabase.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  email text,
  role text not null default 'member' check (role in ('member','admin')),
  plan text not null default 'free' check (plan in ('free','pro')),
  subscription_status text not null default 'inactive',
  subscription_id text,
  is_suspended boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id,display_name,email)
  values(new.id, coalesce(new.raw_user_meta_data->>'display_name', split_part(new.email,'@',1)), new.email)
  on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='admin' and is_suspended=false);
$$;

create table if not exists public.assets (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text default '',
  category text not null default 'Outros',
  subcategory text default '',
  tags text[] not null default '{}',
  media_type text not null default 'archive' check(media_type in ('audio','video','image','archive','project')),
  file_format text,
  file_size bigint,
  cover_url text,
  access_level text not null default 'pro' check(access_level in ('free','pro')),
  status text not null default 'draft' check(status in ('draft','published','paused')),
  download_enabled boolean not null default true,
  preview_enabled boolean not null default true,
  featured boolean not null default false,
  download_count bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.asset_files (
  asset_id uuid primary key references public.assets(id) on delete cascade,
  file_key text,
  preview_key text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tutorials (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text default '',
  category text default 'Edição',
  duration_label text default '',
  thumbnail_url text,
  access_level text not null default 'pro' check(access_level in ('free','pro')),
  status text not null default 'draft' check(status in ('draft','published','paused')),
  featured boolean not null default false,
  order_index integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tutorial_sources (
  tutorial_id uuid primary key references public.tutorials(id) on delete cascade,
  youtube_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.favorites (
  user_id uuid not null references public.profiles(id) on delete cascade,
  asset_id uuid not null references public.assets(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(user_id,asset_id)
);

create table if not exists public.downloads (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  asset_id uuid references public.assets(id) on delete set null,
  action text not null default 'download',
  ip_hash text,
  created_at timestamptz not null default now()
);
create index if not exists downloads_user_date_idx on public.downloads(user_id,created_at desc);
create index if not exists downloads_asset_date_idx on public.downloads(asset_id,created_at desc);

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

insert into public.app_settings(key,value) values
  ('hero_youtube_id','""'::jsonb),
  ('pro_price','"19,90"'::jsonb),
  ('discord_url','""'::jsonb),
  ('whatsapp_url','""'::jsonb),
  ('download_daily_limit','1000'::jsonb),
  ('global_downloads_enabled','true'::jsonb),
  ('maintenance_message','""'::jsonb)
on conflict(key) do nothing;

create or replace function public.increment_asset_download(asset_uuid uuid)
returns void language sql security definer set search_path=public as $$
  update public.assets set download_count=download_count+1 where id=asset_uuid;
$$;

-- Updated_at triggers
DO $$
BEGIN
  if not exists(select 1 from pg_trigger where tgname='profiles_updated_at') then create trigger profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at(); end if;
  if not exists(select 1 from pg_trigger where tgname='assets_updated_at') then create trigger assets_updated_at before update on public.assets for each row execute function public.set_updated_at(); end if;
  if not exists(select 1 from pg_trigger where tgname='asset_files_updated_at') then create trigger asset_files_updated_at before update on public.asset_files for each row execute function public.set_updated_at(); end if;
  if not exists(select 1 from pg_trigger where tgname='tutorials_updated_at') then create trigger tutorials_updated_at before update on public.tutorials for each row execute function public.set_updated_at(); end if;
  if not exists(select 1 from pg_trigger where tgname='tutorial_sources_updated_at') then create trigger tutorial_sources_updated_at before update on public.tutorial_sources for each row execute function public.set_updated_at(); end if;
END $$;

alter table public.profiles enable row level security;
alter table public.assets enable row level security;
alter table public.asset_files enable row level security;
alter table public.tutorials enable row level security;
alter table public.tutorial_sources enable row level security;
alter table public.favorites enable row level security;
alter table public.downloads enable row level security;
alter table public.app_settings enable row level security;

-- Drop policies if re-running this file.
drop policy if exists profiles_read on public.profiles;
drop policy if exists profiles_admin_update on public.profiles;
drop policy if exists assets_catalog on public.assets;
drop policy if exists assets_admin_insert on public.assets;
drop policy if exists assets_admin_update on public.assets;
drop policy if exists assets_admin_delete on public.assets;
drop policy if exists asset_files_admin on public.asset_files;
drop policy if exists tutorials_catalog on public.tutorials;
drop policy if exists tutorials_admin_insert on public.tutorials;
drop policy if exists tutorials_admin_update on public.tutorials;
drop policy if exists tutorials_admin_delete on public.tutorials;
drop policy if exists tutorial_sources_admin on public.tutorial_sources;
drop policy if exists favorites_read on public.favorites;
drop policy if exists favorites_insert on public.favorites;
drop policy if exists favorites_delete on public.favorites;
drop policy if exists downloads_read on public.downloads;
drop policy if exists settings_read on public.app_settings;
drop policy if exists settings_admin on public.app_settings;

create policy profiles_read on public.profiles for select using (id=auth.uid() or public.is_admin());
create policy profiles_admin_update on public.profiles for update using (public.is_admin()) with check (public.is_admin());

create policy assets_catalog on public.assets for select using (status='published' or public.is_admin());
create policy assets_admin_insert on public.assets for insert with check (public.is_admin());
create policy assets_admin_update on public.assets for update using (public.is_admin()) with check (public.is_admin());
create policy assets_admin_delete on public.assets for delete using (public.is_admin());
create policy asset_files_admin on public.asset_files for all using (public.is_admin()) with check (public.is_admin());

create policy tutorials_catalog on public.tutorials for select using (status='published' or public.is_admin());
create policy tutorials_admin_insert on public.tutorials for insert with check (public.is_admin());
create policy tutorials_admin_update on public.tutorials for update using (public.is_admin()) with check (public.is_admin());
create policy tutorials_admin_delete on public.tutorials for delete using (public.is_admin());
create policy tutorial_sources_admin on public.tutorial_sources for all using (public.is_admin()) with check (public.is_admin());

create policy favorites_read on public.favorites for select using (user_id=auth.uid() or public.is_admin());
create policy favorites_insert on public.favorites for insert with check (user_id=auth.uid());
create policy favorites_delete on public.favorites for delete using (user_id=auth.uid() or public.is_admin());

create policy downloads_read on public.downloads for select using (user_id=auth.uid() or public.is_admin());
create policy settings_read on public.app_settings for select using (true);
create policy settings_admin on public.app_settings for all using (public.is_admin()) with check (public.is_admin());

-- Explicit grants. Secrets/keys never live in these tables.
grant usage on schema public to anon, authenticated;
grant select on public.assets, public.tutorials, public.app_settings to anon, authenticated;
grant select on public.profiles, public.favorites, public.downloads to authenticated;
grant insert,delete on public.favorites to authenticated;
grant insert,update,delete on public.assets, public.tutorials, public.app_settings to authenticated;
grant select,insert,update,delete on public.asset_files, public.tutorial_sources to authenticated;
grant update on public.profiles to authenticated;
grant usage,select on sequence public.downloads_id_seq to authenticated;
revoke all on function public.increment_asset_download(uuid) from public, anon, authenticated;
grant execute on function public.increment_asset_download(uuid) to service_role;

-- Depois de criar sua primeira conta, transforme-a em admin:
-- update public.profiles set role='admin' where email='SEU_EMAIL';

-- === DEHAX V2.2 — comunidade, categorias, checkout, CRM e VOD ===
alter table public.profiles add column if not exists pro_started_at timestamptz;
alter table public.profiles add column if not exists access_expires_at timestamptz;
alter table public.profiles add column if not exists attribution jsonb not null default '{}'::jsonb;

create table if not exists public.asset_categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  description text default '',
  status text not null default 'active' check(status in ('active','paused')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table if not exists public.asset_subcategories (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.asset_categories(id) on delete cascade,
  name text not null,
  slug text not null,
  status text not null default 'active' check(status in ('active','paused')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(category_id,name), unique(category_id,slug)
);
alter table public.assets add column if not exists category_id uuid references public.asset_categories(id) on delete set null;
alter table public.assets add column if not exists subcategory_id uuid references public.asset_subcategories(id) on delete set null;
alter table public.tutorials add column if not exists unlock_after_days integer not null default 0 check(unlock_after_days between 0 and 365);

create table if not exists public.payment_orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  provider text not null default 'mercadopago',
  provider_order_id text unique,
  kind text not null check(kind in ('pix','subscription')),
  status text not null default 'pending',
  amount numeric(12,2),
  access_days integer,
  raw jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists payment_orders_user_idx on public.payment_orders(user_id,created_at desc);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  anonymous_id text,
  session_id text,
  event_name text not null,
  path text,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  fbclid text,
  metadata jsonb not null default '{}'::jsonb,
  ip_hash text,
  created_at timestamptz not null default now()
);
create index if not exists analytics_events_created_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_anon_idx on public.analytics_events(anonymous_id,created_at desc);
create index if not exists analytics_events_user_idx on public.analytics_events(user_id,created_at desc);

create table if not exists public.vod_history (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  job_id text not null,
  source_url text,
  title text,
  status text not null default 'queued',
  format text,
  quality text,
  output_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id,job_id)
);

insert into public.asset_categories(name,slug,description,sort_order) values
 ('SFX','sfx','Efeitos sonoros para ritmo, impacto e humor.',10),
 ('Memes','memes','Memes e reactions para edição de gameplays.',20),
 ('Músicas','musicas','Trilhas para conteúdo gamer.',30),
 ('Transições','transicoes','Transições e elementos de passagem.',40),
 ('Overlays','overlays','HUD, elementos gráficos e sobreposições.',50),
 ('Presets','presets','Presets e configurações prontas.',60),
 ('LUTs','luts','Looks e LUTs para colorização.',70),
 ('Templates','templates','Templates e projetos editáveis.',80)
on conflict(name) do nothing;

insert into public.asset_subcategories(category_id,name,slug,sort_order)
select c.id,v.name,v.slug,v.ord from public.asset_categories c join (values
 ('SFX','Whoosh','whoosh',10),('SFX','Impact','impact',20),('SFX','UI','ui',30),('SFX','Ambience','ambience',40),
 ('Memes','Reaction','reaction',10),('Memes','Fails','fails',20),('Memes','Viral','viral',30),
 ('Músicas','Electronic','electronic',10),('Músicas','Cinematic','cinematic',20),('Músicas','Lo-fi','lofi',30),
 ('Transições','Glitch','glitch',10),('Transições','Whip','whip',20),('Transições','Zoom','zoom',30),
 ('Overlays','HUD','hud',10),('Overlays','Film','film',20),('Presets','Premiere','premiere',10),('Presets','DaVinci','davinci',20),
 ('LUTs','Gaming','gaming',10),('Templates','YouTube','youtube',10)
) as v(cat,name,slug,ord) on c.name=v.cat
on conflict(category_id,name) do nothing;

insert into public.app_settings(key,value) values
 ('landing_eyebrow','"A comunidade para editores de gameplays"'::jsonb),
 ('landing_title','"EDITE MAIS RÁPIDO. CRIE MELHOR."'::jsonb),
 ('landing_copy','"Tutoriais, assets, memes, SFX, músicas e transições em uma biblioteca feita para quem edita conteúdo gamer."'::jsonb),
 ('landing_cta_text','"QUERO FAZER PARTE"'::jsonb),
 ('showcase_heading','"VEJA OS ASSETS NA PRÁTICA."'::jsonb),
 ('showcase_youtube_1','""'::jsonb),('showcase_youtube_2','""'::jsonb),('showcase_youtube_3','""'::jsonb),
 ('showcase_title_1','"Sound design em gameplay"'::jsonb),('showcase_title_2','"Memes e timing"'::jsonb),('showcase_title_3','"Transições e impacto"'::jsonb),
 ('brand_logo_url','"/assets/brand/dehax-logo.png"'::jsonb),
 ('brand_red','"#ff294d"'::jsonb),('brand_cyan','"#00d9ff"'::jsonb),('brand_background','"#05070a"'::jsonb),
 ('meta_pixel_id','""'::jsonb),('pix_access_days','30'::jsonb),('renewal_notice_days','7'::jsonb),
 ('support_email','""'::jsonb),('business_name','"DeHax Editor"'::jsonb),('business_document','""'::jsonb),
 ('public_site_content','{}'::jsonb)
on conflict(key) do nothing;

DO $$ BEGIN
 if not exists(select 1 from pg_trigger where tgname='asset_categories_updated_at') then create trigger asset_categories_updated_at before update on public.asset_categories for each row execute function public.set_updated_at(); end if;
 if not exists(select 1 from pg_trigger where tgname='asset_subcategories_updated_at') then create trigger asset_subcategories_updated_at before update on public.asset_subcategories for each row execute function public.set_updated_at(); end if;
 if not exists(select 1 from pg_trigger where tgname='payment_orders_updated_at') then create trigger payment_orders_updated_at before update on public.payment_orders for each row execute function public.set_updated_at(); end if;
 if not exists(select 1 from pg_trigger where tgname='vod_history_updated_at') then create trigger vod_history_updated_at before update on public.vod_history for each row execute function public.set_updated_at(); end if;
END $$;

alter table public.asset_categories enable row level security;
alter table public.asset_subcategories enable row level security;
alter table public.payment_orders enable row level security;
alter table public.analytics_events enable row level security;
alter table public.vod_history enable row level security;

drop policy if exists asset_categories_read on public.asset_categories;
drop policy if exists asset_categories_admin on public.asset_categories;
drop policy if exists asset_subcategories_read on public.asset_subcategories;
drop policy if exists asset_subcategories_admin on public.asset_subcategories;
drop policy if exists payment_orders_read on public.payment_orders;
drop policy if exists analytics_events_admin on public.analytics_events;
drop policy if exists vod_history_read on public.vod_history;
create policy asset_categories_read on public.asset_categories for select using(status='active' or public.is_admin());
create policy asset_categories_admin on public.asset_categories for all using(public.is_admin()) with check(public.is_admin());
create policy asset_subcategories_read on public.asset_subcategories for select using(status='active' or public.is_admin());
create policy asset_subcategories_admin on public.asset_subcategories for all using(public.is_admin()) with check(public.is_admin());
create policy payment_orders_read on public.payment_orders for select using(user_id=auth.uid() or public.is_admin());
create policy analytics_events_admin on public.analytics_events for select using(public.is_admin());
create policy vod_history_read on public.vod_history for select using(user_id=auth.uid() or public.is_admin());

grant select on public.asset_categories, public.asset_subcategories to anon,authenticated;
grant select on public.payment_orders, public.vod_history to authenticated;
grant select on public.analytics_events to authenticated;
grant insert,update,delete on public.asset_categories,public.asset_subcategories to authenticated;
grant usage,select on sequence public.analytics_events_id_seq to authenticated;

-- === DEHAX V2.2.1 — checkout Mercado Pago + planos mensal/semestral ===
alter table public.payment_orders add column if not exists plan_code text;
alter table public.payment_orders add column if not exists payment_method text;
alter table public.payment_orders add column if not exists access_granted_at timestamptz;
alter table public.payment_orders drop constraint if exists payment_orders_kind_check;
alter table public.payment_orders add constraint payment_orders_kind_check check (kind in ('pix','subscription','card_once'));
insert into public.app_settings(key,value) values
 ('pro_monthly_price','"19,90"'::jsonb),
 ('pro_semester_monthly_equiv','"9,90"'::jsonb),
 ('pro_semester_total','"59,40"'::jsonb),
 ('pix_access_days','30'::jsonb),
 ('renewal_notice_days','7'::jsonb)
on conflict(key) do nothing;

-- Concessão atômica/idempotente de acesso pré-pago (Pix mensal, Pix semestral ou cartão semestral).
drop function if exists public.grant_fixed_pro_for_order(uuid,integer);
drop function if exists public.grant_fixed_pro_for_order(uuid);
create or replace function public.grant_fixed_pro_for_order(p_order_id uuid)
returns timestamptz
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order public.payment_orders%rowtype;
  v_profile public.profiles%rowtype;
  v_base timestamptz;
  v_until timestamptz;
  v_status text;
  v_days integer;
begin
  select * into v_order from public.payment_orders where id = p_order_id for update;
  if not found then raise exception 'payment order not found'; end if;
  if v_order.kind not in ('pix','card_once') then raise exception 'payment order is not a fixed-access purchase'; end if;
  if coalesce(v_order.plan_code,'') not in ('monthly','semester') then raise exception 'invalid fixed-access plan'; end if;

  select * into v_profile from public.profiles where id = v_order.user_id for update;
  if not found then raise exception 'profile not found'; end if;
  if v_order.access_granted_at is not null then return v_profile.access_expires_at; end if;

  -- Renovação antecipada nunca perde dias: se o membro ainda tem acesso,
  -- o novo período começa somente depois da expiração atual.
  v_base := case when v_profile.access_expires_at is not null and v_profile.access_expires_at > now()
                 then v_profile.access_expires_at else now() end;

  if v_order.plan_code = 'monthly' then
    v_days := greatest(1,coalesce(v_order.access_days,30));
    v_until := v_base + make_interval(days => v_days);
    v_status := 'pix_active';
  else
    v_until := v_base + make_interval(months => 6);
    v_status := 'semester_active';
  end if;

  update public.profiles
     set plan='pro',
         subscription_status=v_status,
         subscription_id=null,
         pro_started_at=coalesce(pro_started_at,now()),
         access_expires_at=v_until
   where id=v_order.user_id;

  update public.payment_orders set access_granted_at=now() where id=p_order_id;
  return v_until;
end $$;
revoke all on function public.grant_fixed_pro_for_order(uuid) from public,anon,authenticated;
grant execute on function public.grant_fixed_pro_for_order(uuid) to service_role;
-- DEHAX V2.2.2 — checkout para novos usuários + vantagens editáveis dos planos
-- Execute uma vez no SQL Editor depois da migration V2.2.1.

create table if not exists public.checkout_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists checkout_sessions_user_idx on public.checkout_sessions(user_id,created_at desc);
create index if not exists checkout_sessions_expiry_idx on public.checkout_sessions(expires_at);
alter table public.checkout_sessions enable row level security;
-- Sem policy para anon/authenticated: somente o backend com service_role acessa esta tabela.
revoke all on table public.checkout_sessions from anon, authenticated;

insert into public.app_settings(key,value) values
  ('free_plan_benefits','["Conta na plataforma","Assets e aulas gratuitas","Visualização da biblioteca PRO"]'::jsonb),
  ('monthly_plan_benefits','["Toda a biblioteca de assets","Todos os tutoriais PRO","Novos conteúdos adicionados","Preview + download direto","Renovação mensal flexível"]'::jsonb),
  ('semester_plan_benefits','["Toda a biblioteca de assets","Todos os tutoriais PRO","Novos conteúdos adicionados","Preview + download direto","6 meses de acesso com maior economia"]'::jsonb)
on conflict(key) do nothing;

-- === DEHAX V2.3.0 — IA de áudio + quotas ===
create table if not exists public.ai_audio_generations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null check(kind in ('narration','sfx')),
  provider text not null default 'elevenlabs',
  model_id text,
  voice_id text,
  prompt_preview text default '',
  tokens_spent integer not null default 0 check(tokens_spent >= 0),
  file_key text,
  file_size bigint not null default 0 check(file_size >= 0),
  duration_seconds numeric(8,2),
  status text not null default 'ready' check(status in ('processing','ready','failed','expired','deleted')),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ai_audio_generations_user_created_idx on public.ai_audio_generations(user_id,created_at desc);
create index if not exists ai_audio_generations_expiry_idx on public.ai_audio_generations(expires_at) where status='ready';
DO $$ BEGIN
 if not exists(select 1 from pg_trigger where tgname='ai_audio_generations_updated_at') then create trigger ai_audio_generations_updated_at before update on public.ai_audio_generations for each row execute function public.set_updated_at(); end if;
END $$;
alter table public.ai_audio_generations enable row level security;
drop policy if exists ai_audio_generations_read on public.ai_audio_generations;
create policy ai_audio_generations_read on public.ai_audio_generations for select using(user_id=auth.uid() or public.is_admin());
revoke all on public.ai_audio_generations from anon;
revoke insert,update,delete on public.ai_audio_generations from authenticated;
grant select on public.ai_audio_generations to authenticated;
insert into public.app_settings(key,value) values
 ('ai_audio_enabled','false'::jsonb),('ai_audio_provider','"elevenlabs"'::jsonb),('ai_audio_pro_tokens_per_cycle','150'::jsonb),('ai_audio_token_cycle_days','30'::jsonb),('ai_audio_narration_tokens_per_1000_chars','55'::jsonb),('ai_audio_narration_hq_tokens_per_1000_chars','55'::jsonb),('ai_audio_narration_flash_tokens_per_1000_chars','28'::jsonb),('ai_audio_sfx_tokens_per_second','1'::jsonb),('ai_audio_storage_days','30'::jsonb),('ai_audio_storage_gb_per_user','1'::jsonb),('ai_audio_max_narration_chars','5000'::jsonb),('ai_audio_max_sfx_seconds','30'::jsonb),('ai_audio_voice_limit','30'::jsonb)
on conflict(key) do nothing;

-- V2.3.0 — reserva atômica de tokens da IA
create or replace function public.reserve_ai_audio_generation(
  p_id uuid,p_user_id uuid,p_kind text,p_provider text,p_model_id text,p_voice_id text,p_prompt_preview text,p_tokens integer,p_expires_at timestamptz,p_cycle_start timestamptz,p_cycle_end timestamptz,p_token_limit integer default null
) returns integer language plpgsql security definer set search_path=public as $$
declare v_used integer := 0; v_remaining integer;
begin
  perform 1 from public.profiles where id=p_user_id for update;
  if not found then raise exception 'profile not found'; end if;
  select coalesce(sum(tokens_spent),0)::integer into v_used from public.ai_audio_generations where user_id=p_user_id and created_at>=p_cycle_start and created_at<p_cycle_end and status in ('processing','ready','expired','deleted');
  if p_token_limit is not null and v_used+p_tokens>p_token_limit then raise exception 'AI_TOKEN_LIMIT|%|%',p_tokens,greatest(0,p_token_limit-v_used); end if;
  insert into public.ai_audio_generations(id,user_id,kind,provider,model_id,voice_id,prompt_preview,tokens_spent,file_size,duration_seconds,status,expires_at) values(p_id,p_user_id,p_kind,p_provider,p_model_id,p_voice_id,p_prompt_preview,p_tokens,0,null,'processing',p_expires_at);
  if p_token_limit is null then return null; end if;
  v_remaining:=greatest(0,p_token_limit-(v_used+p_tokens)); return v_remaining;
end $$;
revoke all on function public.reserve_ai_audio_generation(uuid,uuid,text,text,text,text,text,integer,timestamptz,timestamptz,timestamptz,integer) from public,anon,authenticated;
grant execute on function public.reserve_ai_audio_generation(uuid,uuid,text,text,text,text,text,integer,timestamptz,timestamptz,timestamptz,integer) to service_role;
-- DEHAX V2.3.3 — retenção, suporte, reembolso e ID público de compra.
-- Execute UMA VEZ depois da migration-v2.3.1.sql.

create extension if not exists pgcrypto;

create or replace function public.dehax_purchase_code()
returns text
language sql
volatile
set search_path=public
as $$
  select 'DHX-' || to_char(clock_timestamp(),'YYMMDD') || '-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,10));
$$;

alter table public.payment_orders add column if not exists purchase_code text;
alter table public.payment_orders add column if not exists confirmation_email_sent_at timestamptz;
update public.payment_orders set purchase_code=public.dehax_purchase_code() where purchase_code is null or btrim(purchase_code)='';
alter table public.payment_orders alter column purchase_code set default public.dehax_purchase_code();
alter table public.payment_orders alter column purchase_code set not null;
create unique index if not exists payment_orders_purchase_code_uidx on public.payment_orders(purchase_code);

create table if not exists public.subscription_exit_feedback (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  subscription_id text,
  plan_code text not null check(plan_code in ('monthly','semester')),
  reason text not null,
  decision text not null check(decision in ('kept_with_offer','canceled','will_not_renew')),
  created_at timestamptz not null default now()
);
create index if not exists subscription_exit_feedback_user_idx on public.subscription_exit_feedback(user_id,created_at desc);

create table if not exists public.retention_offers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  subscription_id text,
  plan_code text not null check(plan_code in ('monthly','semester')),
  discount_percent numeric(5,2) not null default 10,
  original_amount numeric(12,2),
  discounted_amount numeric(12,2),
  cycles_total integer,
  cycles_used integer not null default 0,
  status text not null default 'active' check(status in ('active','completed','canceled','redeemed','expired')),
  activated_at timestamptz not null default now(),
  completed_at timestamptz,
  redeemed_order_id uuid references public.payment_orders(id) on delete set null,
  provider_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists retention_offers_user_idx on public.retention_offers(user_id,created_at desc);
create index if not exists retention_offers_active_idx on public.retention_offers(status,plan_code) where status='active';
create unique index if not exists retention_offers_one_active_uidx on public.retention_offers(user_id,plan_code) where status='active';

create table if not exists public.refund_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  payment_order_id uuid not null references public.payment_orders(id) on delete restrict,
  purchase_code text not null,
  purchase_date timestamptz not null,
  eligibility_deadline timestamptz not null,
  phone text not null,
  cpf text not null,
  address jsonb not null default '{}'::jsonb,
  status text not null default 'pending' check(status in ('pending','reviewing','approved','rejected','completed')),
  admin_note text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists refund_requests_user_idx on public.refund_requests(user_id,created_at desc);
create index if not exists refund_requests_status_idx on public.refund_requests(status,created_at desc);
create unique index if not exists refund_requests_open_order_uidx on public.refund_requests(payment_order_id) where status in ('pending','reviewing','approved');

DO $$ BEGIN
  if not exists(select 1 from pg_trigger where tgname='retention_offers_updated_at') then
    create trigger retention_offers_updated_at before update on public.retention_offers for each row execute function public.set_updated_at();
  end if;
  if not exists(select 1 from pg_trigger where tgname='refund_requests_updated_at') then
    create trigger refund_requests_updated_at before update on public.refund_requests for each row execute function public.set_updated_at();
  end if;
END $$;

alter table public.subscription_exit_feedback enable row level security;
alter table public.retention_offers enable row level security;
alter table public.refund_requests enable row level security;

drop policy if exists subscription_exit_feedback_admin on public.subscription_exit_feedback;
drop policy if exists retention_offers_admin on public.retention_offers;
drop policy if exists refund_requests_admin on public.refund_requests;
drop policy if exists refund_requests_admin_update on public.refund_requests;
create policy subscription_exit_feedback_admin on public.subscription_exit_feedback for select using(public.is_admin());
create policy retention_offers_admin on public.retention_offers for select using(public.is_admin());
create policy refund_requests_admin on public.refund_requests for select using(public.is_admin());
create policy refund_requests_admin_update on public.refund_requests for update using(public.is_admin()) with check(public.is_admin());

revoke all on public.subscription_exit_feedback,public.retention_offers,public.refund_requests from anon;
revoke insert,update,delete on public.subscription_exit_feedback,public.retention_offers from authenticated;
revoke insert,delete on public.refund_requests from authenticated;
grant select on public.subscription_exit_feedback,public.retention_offers,public.refund_requests to authenticated;
grant update on public.refund_requests to authenticated;

insert into public.app_settings(key,value) values
  ('retention_discount_percent','10'::jsonb),
  ('retention_monthly_cycles','3'::jsonb),
  ('refund_request_days','7'::jsonb)
on conflict(key) do nothing;

-- V3.0.0 — hierarquia visual da biblioteca, tags por categoria e preparação de metadados
create table if not exists public.asset_subcategory_links (
  id uuid primary key default gen_random_uuid(),
  parent_subcategory_id uuid not null references public.asset_subcategories(id) on delete cascade,
  child_subcategory_id uuid not null references public.asset_subcategories(id) on delete cascade,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  constraint asset_subcategory_links_distinct check (parent_subcategory_id <> child_subcategory_id),
  constraint asset_subcategory_links_unique unique (parent_subcategory_id, child_subcategory_id)
);
create index if not exists idx_asset_subcategory_links_parent on public.asset_subcategory_links(parent_subcategory_id,sort_order);
create index if not exists idx_asset_subcategory_links_child on public.asset_subcategory_links(child_subcategory_id);
create table if not exists public.asset_category_tags (
  id uuid primary key default gen_random_uuid(),
  category_id uuid not null references public.asset_categories(id) on delete cascade,
  name text not null,
  slug text not null,
  status text not null default 'active' check(status in ('active','paused')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint asset_category_tags_name_unique unique(category_id,name),
  constraint asset_category_tags_slug_unique unique(category_id,slug)
);
create index if not exists idx_asset_category_tags_category on public.asset_category_tags(category_id,sort_order);
alter table public.assets add column if not exists metadata_status text not null default 'pending';
alter table public.assets add column if not exists metadata_version integer not null default 0;
alter table public.assets drop constraint if exists assets_metadata_status_check;
alter table public.assets add constraint assets_metadata_status_check check(metadata_status in ('pending','applied','unsupported','error'));
do $$ begin
 if not exists(select 1 from pg_trigger where tgname='asset_category_tags_updated_at') then create trigger asset_category_tags_updated_at before update on public.asset_category_tags for each row execute function public.set_updated_at(); end if;
end $$;
alter table public.asset_subcategory_links enable row level security;
alter table public.asset_category_tags enable row level security;
drop policy if exists asset_subcategory_links_read on public.asset_subcategory_links;
drop policy if exists asset_subcategory_links_admin on public.asset_subcategory_links;
drop policy if exists asset_category_tags_read on public.asset_category_tags;
drop policy if exists asset_category_tags_admin on public.asset_category_tags;
create policy asset_subcategory_links_read on public.asset_subcategory_links for select using(true);
create policy asset_subcategory_links_admin on public.asset_subcategory_links for all using(public.is_admin()) with check(public.is_admin());
create policy asset_category_tags_read on public.asset_category_tags for select using(status='active' or public.is_admin());
create policy asset_category_tags_admin on public.asset_category_tags for all using(public.is_admin()) with check(public.is_admin());
grant select on public.asset_subcategory_links,public.asset_category_tags to anon,authenticated;
grant insert,update,delete on public.asset_subcategory_links,public.asset_category_tags to authenticated;
